# Generated by Django 3.2.3 on 2021-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addint',
            name='c_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='addint',
            name='c_post',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Applied'),
        ),
        migrations.AlterField(
            model_name='addint',
            name='c_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company URL'),
        ),
        migrations.AlterField(
            model_name='addint',
            name='date_applied',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addint',
            name='que_asked',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Questions Asked'),
        ),
        migrations.AlterField(
            model_name='addint',
            name='rec_called',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the Reruiter Call'),
        ),
        migrations.AlterField(
            model_name='addint',
            name='resp_status',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Selected for Next Round', 'Selected for Next Round'), ('Rejected', 'Rejected'), ('No Update', 'No Update')], max_length=100, null=True, verbose_name='Response Status'),
        ),
        migrations.AlterField(
            model_name='addint',
            name='scd_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addint',
            name='self_analysis',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Self Analysis'),
        ),
    ]
